language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
      dotnet: 2.1.3
      sudo: required
      env: MONO_BASE_PATH=/usr/lib/mono/
    - os: osx
      osx_image: xcode9.2
      mono: latest
      dotnet: 2.1.3
      sudo: required
      env: MONO_BASE_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
        key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - dotnet-dev-1.1.6
      - dotnet-sdk-2.1.3
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
      curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version "1.1.6" --install-dir "$DOTNET_INSTALL_DIR" --no-path
      curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version "2.1.3" --install-dir "$DOTNET_INSTALL_DIR" --no-path
      export PATH="$DOTNET_INSTALL_DIR:$PATH"
    fi
script:
  - FrameworkPathOverride=$MONO_BASE_PATH/4.5-api/ $(pwd)/tools/build.sh '-target=Test' "-softwareVersion=$(git describe --abbrev=0 --tags | cut -c 2-)"
notifications:
  email: false