version: BUILD {build}
image: Visual Studio 2017
before_build:
  - ps: |
      $mostRecentTag = git describe --abbrev=0 --tags
      $mostRecentVersion = $mostRecentTag.Substring(1)
      $currentCommitHash = git rev-parse --short HEAD
      Set-AppveyorBuildVariable -Name SW_VER -Value $mostRecentVersion
      Update-AppveyorBuild -Version "Build $env:APPVEYOR_BUILD_NUMBER - Commit $currentCommitHash - Tag v$env:SW_VER"
build_script:
  - ps: |
      $additionalArgs = if ($env:APPVEYOR_REPO_TAG -ne 'true') { "-buildNumber=$env:APPVEYOR_BUILD_NUMBER" }
      .\tools\build.ps1 '-target=Pack' "-softwareVersion=$env:SW_VER" $additionalArgs
after_build:
artifacts:
  - path: tools\artifacts\*.nupkg
deploy:
  provider: NuGet
  api_key:
      secure: GcyRYCPxp53YxLHBjdeBRQeGimm4CJDDMnZFNQ1gb03PDAsR6Mp7PMWKzc7vjPKP
  skip_symbols: false
  on:
      appveyor_repo_tag: true