configuration: Release
platform: Any CPU
before_build:
  - ps: Set-AppveyorBuildVariable -Name NGP_VER -Value (& "$env:APPVEYOR_BUILD_FOLDER\tools\get-version.ps1" -versionInfoFile "$env:APPVEYOR_BUILD_FOLDER\src\NLog.Targets.Syslog\Properties\AssemblyInfo.cs")
  - ps: Update-AppveyorBuild -Version "$env:NGP_VER.$env:APPVEYOR_BUILD_NUMBER"
  - ps: (Get-Content "$env:APPVEYOR_BUILD_FOLDER\src\NLog.Targets.Syslog\Properties\AssemblyInfo.cs") -replace '(AssemblyFileVersion\(\")([\.0-9]+)(\"\)])',"`${1}$env:APPVEYOR_BUILD_VERSION`${3}" | Set-Content "$env:APPVEYOR_BUILD_FOLDER\src\NLog.Targets.Syslog\Properties\AssemblyInfo.cs"
build_script:
  - ps: .\tools\build.ps1 "$env:NGP_VER"
after_build:
  - cmd: nuget pack src/NLog.Targets.Syslog/NLog.Targets.Syslog.Schema.nuspec -Prop version=%NGP_VER%
artifacts:
  - path: '*.nupkg'
