version: BUILD {build}
image: Visual Studio 2017
skip_branch_with_pr: true
environment:
  NUGET_API_KEY:
    secure: +Z/sH3FwRcvcnfBZn6dzy8MRi7N10hqh6Lq2MPua3AGtVvvT7sqw2nxENKG3g0/6
install:
  - ps: |
      $DOTNET_INSTALL_DIR = $(Join-Path (Get-Location) 'dotnetsdk')
      powershell -NoProfile -ExecutionPolicy Unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Version 1.1.11 -InstallDir $DOTNET_INSTALL_DIR -NoPath"
      powershell -NoProfile -ExecutionPolicy Unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Version 2.1.503 -InstallDir $DOTNET_INSTALL_DIR -NoPath"
      powershell -NoProfile -ExecutionPolicy Unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Version 2.2.103 -InstallDir $DOTNET_INSTALL_DIR -NoPath"
      $env:Path = "$DOTNET_INSTALL_DIR;$env:Path"
before_build:
  - ps: |
      $mostRecentTag = git describe --abbrev=0 --tags --always
      if ($mostRecentTag.Substring(0, 1) -ne 'v') {
          $mostRecentTag = 'v1.0.0'
          if ($env:APPVEYOR_REPO_TAG -eq 'true') { exit 1 }
      }
      $mostRecentVersion = $mostRecentTag.Substring(1)
      $currentCommitHash = git rev-parse --short HEAD
      Set-AppveyorBuildVariable -Name SW_VER -Value $mostRecentVersion
      Update-AppveyorBuild -Version "Build $env:APPVEYOR_BUILD_NUMBER - Commit $currentCommitHash - Tag v$mostRecentVersion"
build_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -ne 'true') {
          .\tools\build.ps1 '--target=NuGetPack' "--softwareVersion=$env:SW_VER" "--buildNumber=$env:APPVEYOR_BUILD_NUMBER"
      }
      else {
          .\tools\build.ps1 '--target=NuGetPush' "--softwareVersion=$env:SW_VER" '--nuGetSource=https://api.nuget.org/v3/index.json' "--nuGetApiKey=$env:NUGET_API_KEY"
      }
      if ($LastExitCode -ne 0) { exit $LastExitCode }
after_build:
  - ps: |
      .\tools\build.ps1 '--target=ZipArtifacts'
      Push-AppveyorArtifact .\tools\artifacts\artifacts.zip -FileName "artifacts_$env:APPVEYOR_BUILD_ID.zip"
test: off